### ISSUE TITLE
random_word module not found

### ISSUE THREAD

**Issue by m-kruth** [RapidCompiler/Hangman-Game#2]
I get the following error when attempting to run this. Is random_word a self-written module or something that can be installed via pip? If it is a personal module then pushing it to origin would likely solve this problem. T_T is was so excited to play

Error message:
```zsh
user@users-MacBook-Pro Hangman-Game % python Hangman.py                                       
Traceback (most recent call last):
  File "Hangman.py", line 1, in <module>
    from random_word import RandomWords
ImportError: No module named random_word
```

**Comment by RapidCompiler** [comment]
It is a module which needs to be installed via pip.

pip install Random words

This would be the command for installing it on the terminal.

For more info on this, please visit
pypi.org

**Comment by RapidCompiler** [comment]
This module would have to be install via pip. The command to install it is

`pip install Random-Word`
